In [43]:
# null_control
# 1 : null값을 최빈값으로 변경, 
# 2 : null값을 삭제
null_control = 1


In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import numpy as np

In [45]:
url = '../data//(최종)_서울열선_광진도로.csv'

In [46]:
data = pd.read_csv(url)

In [47]:
data.columns

Index(['도로명', '열선', '도로 종류', '시작점_위도', '시작점_경도', '종료점_위도', '종료점_경도', '중앙점_위도',
       '중앙점_경도', '도로_길이', '도로폭', '도로규모', '행정구역', '고도의_차이', '경사각', '최근접_시설들_거리',
       '최근접_시설의_평균거리', '2019_평균_온도', '2020_평균_온도', '2021_평균_온도', '2022_평균_온도',
       '2023_평균_온도', '2024_평균_온도', '종합_평균_기온', '행정동', '생활인구', '최근접_시설들_최소거리',
       '최근접_시설들_최대거리'],
      dtype='object')

In [48]:
data['최근접_시설들_최소거리'] = data['최근접_시설들_거리'].apply(lambda x: np.min(list(map(float, x.split(',')))))
data['최근접_시설들_최대거리'] = data['최근접_시설들_거리'].apply(lambda x: np.max(list(map(float, x.split(',')))))

In [49]:
data.columns

Index(['도로명', '열선', '도로 종류', '시작점_위도', '시작점_경도', '종료점_위도', '종료점_경도', '중앙점_위도',
       '중앙점_경도', '도로_길이', '도로폭', '도로규모', '행정구역', '고도의_차이', '경사각', '최근접_시설들_거리',
       '최근접_시설의_평균거리', '2019_평균_온도', '2020_평균_온도', '2021_평균_온도', '2022_평균_온도',
       '2023_평균_온도', '2024_평균_온도', '종합_평균_기온', '행정동', '생활인구', '최근접_시설들_최소거리',
       '최근접_시설들_최대거리'],
      dtype='object')

In [50]:
road_width = {
    '폭20-25m' : 22.5,
    '폭15-20m' : 17.5,
    '폭8-10m' : 9.0,
    '폭10-12m' : 11.0,
    '폭6-8m' : 7.0,
    '6m미만' : 5.0
}

data['도로폭'] = data['도로폭'].map(road_width)

In [51]:
road_scale = {
    "소로" : 1,   
    "소로3류" : 2,  
    "소로1류" : 3,
    "소로2류" : 4,
    "중로2류" : 5,
    "중로1류" : 6
}

data['도로규모'] = data['도로규모'].map(road_scale)

In [52]:
road_title = {
    '3차로' : 1,
    '주거지 도로' : 2,
    '생활도로' : 3
}
        
data['도로 종류'] = data['도로 종류'].map(road_title)

In [53]:
print(data['도로폭'].unique())

[22.5  7.   5.   9.  11.  17.5]


In [54]:
print(data['도로규모'].unique())

[6 2 1 4 3 5]


In [55]:
print(data['도로 종류'].unique())

[1 2 3]


In [56]:
if null_control == 1 :
    # 최빈값을 대입
    for col in ['경사각', '최근접_시설의_평균거리', '도로규모', '도로 종류', '열선', '도로폭', '2019_평균_온도', '2020_평균_온도', '2021_평균_온도',
       '2022_평균_온도', '2023_평균_온도', '2024_평균_온도', '종합_평균_기온']:
        data[col] = data[col].fillna(data[col].mode()[0])
if null_control == 2 :
    # 널값 삭제
    data = data.dropna(subset=['경사각', '최근접_시설의_평균거리', '도로규모', '도로 종류', '열선', '도로폭'])

In [57]:
data.columns

Index(['도로명', '열선', '도로 종류', '시작점_위도', '시작점_경도', '종료점_위도', '종료점_경도', '중앙점_위도',
       '중앙점_경도', '도로_길이', '도로폭', '도로규모', '행정구역', '고도의_차이', '경사각', '최근접_시설들_거리',
       '최근접_시설의_평균거리', '2019_평균_온도', '2020_평균_온도', '2021_평균_온도', '2022_평균_온도',
       '2023_평균_온도', '2024_평균_온도', '종합_평균_기온', '행정동', '생활인구', '최근접_시설들_최소거리',
       '최근접_시설들_최대거리'],
      dtype='object')

In [58]:
X = data[['경사각', '최근접_시설의_평균거리', '도로규모', '도로 종류', '도로폭', 
          '최근접_시설의_평균거리', '최근접_시설들_최소거리', '최근접_시설들_최대거리',
          '생활인구', '종합_평균_기온']]
y = data['열선']  # 라벨값 (1 or 0)

In [59]:
data['최근접_시설들_거리']

0       165.17299640951381 ,141.88730282955694 ,165.97...
1       62.36827510450082 ,84.24249385836922 ,84.24249...
2       117.13714873310688 ,122.47106043434799 ,181.43...
3       170.7456882318119 ,207.35031231752598 ,261.112...
4       119.57304016628333 ,132.2920410496931 ,236.865...
                              ...                        
7154    69.00844434134116 ,94.54668650722202 ,94.54668...
7155    116.97170564924865 ,130.21597401933184 ,122.67...
7156    106.76800390273242 ,123.60699504336469 ,127.95...
7157    74.67855277360383 ,89.30233043522139 ,92.61163...
7158    64.1090520411586 ,104.52316605023508 ,134.9057...
Name: 최근접_시설들_거리, Length: 7159, dtype: object

In [60]:
len(data)

7159

In [61]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.7, random_state=42, stratify=y
)

In [62]:
# 스케일링 (표준화)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## 모델 튜닝

In [63]:
# 랜덤 포레스트 학습
rf_model = RandomForestClassifier(n_estimators=50, random_state=42, max_depth=8)

In [64]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, n_estimators=50, random_state=42)

In [65]:
# 예측 및 평가
y_pred = rf_model.predict(X_test)
y_pred_list = y_pred.tolist()
print(f"랜덤 포레스트 정확도: {accuracy_score(y_test, y_pred):.4f}")

랜덤 포레스트 정확도: 0.9465


In [66]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# 정확도
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# 정밀도
precision = precision_score(y_test, y_pred)
print(f"Precision: {precision}")

# 재현율
recall = recall_score(y_test, y_pred)
print(f"Recall: {recall}")

# F1-Score
f1 = f1_score(y_test, y_pred)
print(f"F1-Score: {f1}")


Accuracy: 0.9464618249534451
Precision: 0.9464285714285714
Recall: 0.6730158730158731
F1-Score: 0.7866419294990723


In [67]:
X_full =  data[['경사각', '최근접_시설의_평균거리', '도로규모', '도로 종류', '도로폭', 
          '최근접_시설의_평균거리', '최근접_시설들_최소거리', '최근접_시설들_최대거리',
          '생활인구', '종합_평균_기온']]  # 특징값
X_full_scaled = scaler.transform(X_full)  

In [68]:
# 전체 데이터 예측
y_full_pred = rf_model.predict(X_full_scaled)

In [69]:
# 예측 결과를 원본 데이터에 추가
data['예측_열선여부'] = y_full_pred

In [70]:
# 예측 결과 출력
print(data[['중앙점_위도', '중앙점_경도', '경사각', '최근접_시설의_평균거리', '열선', '예측_열선여부']].head())  # 예시로 상위 5개만 출력

      중앙점_위도      중앙점_경도       경사각  최근접_시설의_평균거리  열선  예측_열선여부
0  37.490832  127.080852  0.298094    194.979965   1        1
1  37.472200  127.095395  3.326804     90.747029   1        1
2  37.514459  127.053083  5.885870    153.931237   1        1
3  37.523389  127.047251  3.652877    289.545361   1        1
4  37.528873  127.046286  3.251038    291.127352   1        1


In [71]:
# 정확도 평가 (전체 데이터에 대한 예측)
accuracy_full = accuracy_score(data['열선'], y_full_pred)
print(f"전체 데이터에 대한 정확도: {accuracy_full:.4f}")

전체 데이터에 대한 정확도: 0.9540


In [72]:
# 기타 평가 지표
precision_full = precision_score(data['열선'], y_full_pred)
recall_full = recall_score(data['열선'], y_full_pred)
f1_full = f1_score(data['열선'], y_full_pred)

print(f"전체 데이터 정밀도: {precision_full}")
print(f"전체 데이터 재현율: {recall_full}")
print(f"전체 데이터 F1-Score: {f1_full}")

전체 데이터 정밀도: 0.9813333333333333
전체 데이터 재현율: 0.7002854424357755
전체 데이터 F1-Score: 0.8173237090505275


In [73]:
filter_data = data[data['예측_열선여부'] == 1]

In [74]:
filter_data_result = filter_data[filter_data['열선'] == 0]

In [75]:
len(filter_data_result)

14

In [76]:
filter_data_result.columns

Index(['도로명', '열선', '도로 종류', '시작점_위도', '시작점_경도', '종료점_위도', '종료점_경도', '중앙점_위도',
       '중앙점_경도', '도로_길이', '도로폭', '도로규모', '행정구역', '고도의_차이', '경사각', '최근접_시설들_거리',
       '최근접_시설의_평균거리', '2019_평균_온도', '2020_평균_온도', '2021_평균_온도', '2022_평균_온도',
       '2023_평균_온도', '2024_평균_온도', '종합_평균_기온', '행정동', '생활인구', '최근접_시설들_최소거리',
       '최근접_시설들_최대거리', '예측_열선여부'],
      dtype='object')

In [77]:
filter_data_result.reset_index(drop=True, inplace=True)
filter_data_result = filter_data_result.drop_duplicates(subset=['중앙점_위도', '중앙점_경도', '경사각', '최근접_시설의_평균거리', '열선', '예측_열선여부'])


In [78]:
len(filter_data_result)

9

In [79]:
filter_data_result = filter_data_result.reset_index(drop = True)
filter_data_result.head(1)

도로명  열선  도로 종류     시작점_위도      시작점_경도    종료점_위도      종료점_경도     중앙점_위도  \
0  자양강변길   0      2  37.530518  127.071356  37.53077  127.071469  37.530644   

       중앙점_경도      도로_길이  ...  2021_평균_온도  2022_평균_온도 2023_평균_온도  2024_평균_온도  \
0  127.071412  29.767318  ...   -2.121901   -0.870905  -6.477825   -2.790352   

   종합_평균_기온   행정동           생활인구  최근접_시설들_최소거리  최근접_시설들_최대거리  예측_열선여부  
0 -0.804596  자양3동  619954.473071     27.208296    319.661529        1  

[1 rows x 29 columns]

In [80]:
filter_data_result['열선'].value_counts()

열선
0    9
Name: count, dtype: int64

In [81]:
filter_data_result['행정구역'].value_counts()

행정구역
광진구    9
Name: count, dtype: int64

In [82]:
try :
    save_file_url = './make_file/랜덤_포레스트로_분석을_해본_결과.csv'
    data.to_csv(save_file_url, encoding="UTF-8", index=False)
    print(f"{save_file_url} 파일 저장 완료")
except OSError as e :
    print(e)

./make_file/랜덤_포레스트로_분석을_해본_결과.csv 파일 저장 완료


In [83]:
try :
    filter_data_result_url = './make_file/(최종)_랜덤_포로스트_리스트.csv'
    filter_data_result.to_csv(filter_data_result_url, encoding="UTF-8", index=False)
    print(f"{save_file_url} 파일 저장 완료")
except OSError as e :
    print(e)

./make_file/랜덤_포레스트로_분석을_해본_결과.csv 파일 저장 완료
